import{i,a as h,S as b}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const v=document.getElementById("search-form"),y=document.querySelector(".gallery"),d=document.querySelector(".load-more"),w="44548622-5fd69a61f42bc3e999cbd3ef1";let l="",n=1;const f=40;let c=0,m;v.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.target.searchQuery.value.trim(),n=1,y.innerHTML="",d.style.visibility="hidden",l===""){i.warning({title:"Warning",message:"Please enter a search query."});return}try{const r=await p(l,n,f);if(c=r.totalHits,c===0){i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again."});return}i.success({title:"Success",message:`Hooray! We found ${c} images.`}),g(r.hits),r.hits.length<f?i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}):d.style.visibility="visible"}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}});d.addEventListener("click",async()=>{n+=1;try{const t=await p(l,n,f);g(t.hits,!0),n*f>=c&&(d.style.visibility="hidden",i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Failed to load images. Please try again later."})}});async function p(t,r,a){return(await h.get("https://pixabay.com/api/",{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a}})).data}function g(t,r=!1){const a=t.map(s=>`
      <div class="photo-card">
        <a href="${s.largeImageURL}" class="gallery-link">
          <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${s.likes}</p>
          <p class="info-item"><b>Views</b> ${s.views}</p>
          <p class="info-item"><b>Comments</b> ${s.comments}</p>
          <p class="info-item"><b>Downloads</b> ${s.downloads}</p>
        </div>
      </div>
    `).join("");y.insertAdjacentHTML("beforeend",a),m?m.refresh():m=new b(".gallery a",{captionsData:"alt",captionDelay:250}),r&&L()}function L(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
